#!/bin/sh

# set default
DB_HOST=${DB_HOST:-gitlab-postgres}
DB_PORT=${DB_PORT:-5432}
DB_NAME=${DB_NAME:-gitlabhq_production}
DB_USER=${DB_USER:-gitlab}
DB_PASS=${DB_PASS:-gitlabpassword}

REDIS_HOST=${REDIS_HOST:-gitlab-redis}
REDIS_PORT=${REDIS_PORT:-6379}

GITLAB_SECRETS_DB_KEY_BASE=${GITLAB_SECRETS_DB_KEY_BASE:-default}
GITLAB_SECRETS_SECRET_KEY_BASE=${GITLAB_SECRETS_SECRET_KEY_BASE:-default}
GITLAB_SECRETS_OTP_KEY_BASE=${GITLAB_SECRETS_OTP_KEY_BASE:-default}

GITLAB_HTTPS=${GITLAB_HTTPS:-false}
